apiVersion: tf.isaaguilar.com/v1alpha1
kind: Terraform
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "aws-iam-role-service-account.labels" . | nindent 4 }}
spec:
  terraformVersion: {{ .Values.terraform.version }}
  terraformRunnerPullPolicy: IfNotPresent
  terraformModule: {{ .Values.terraform.module }}?ref={{ .Values.terraform.moduleVersion }}
  resourceDownloads:
  - address: https://github.com/appvia/terraform-providers.git//aws/aws.tf?ref=main
  ignoreDelete: false
  {{- with .Values.aws.credentials }}
  credentials:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  serviceAccount: {{ .Values.kubernetes.serviceAccount }}
  env:
  - name: TF_VAR_region
    value: {{ required "You must specify an AWS region!" .Values.aws.region }}
  - name: TF_VAR_role_name
    value: {{ required "You must specify a IAM role name!" .Values.iam.role_name }}
  - name: TF_VAR_cluster_service_accounts
    value: {{ .Values.iam.cluster_service_accounts | toJson | quote }}
  outputsSecret: "{{ .Release.Name }}-outputs"
  customBackend: |-
    terraform {
      backend "kubernetes" {
        secret_suffix    = "{{ .Release.Name }}"
        in_cluster_config  = true
        namespace = "{{ .Release.Namespace }}"
      }
    }
